### 회원가입 성공 요청
# @no-cookie-jar
POST http://localhost:8080/signup
Content-Type: application/json

{
  "username": "bella",
  "password": "12345678",
  "nickname": "정이슬"
}

### 회원가입 실패 - 중복 사용자
POST http://localhost:8080/signup
Content-Type: application/json

{
  "username": "bella",
  "password": "newpass",
  "nickname": "다른 정이슬"
}
